"""Stable HFSS workflow contract constants shared by config and runners."""

HFSS_PROJECT_MODEL_PER_DESIGN = "per_design_project"
HFSS_PROJECT_MODEL_SINGLE_AEDT = "single_aedt_project_multiple_designs"
HFSS_PROJECT_MODELS = (HFSS_PROJECT_MODEL_PER_DESIGN, HFSS_PROJECT_MODEL_SINGLE_AEDT)

HFSS_PROJECT_ACTION_NEW = "new"
HFSS_PROJECT_ACTION_ADD = "add"
HFSS_PROJECT_ACTIONS = (HFSS_PROJECT_ACTION_NEW, HFSS_PROJECT_ACTION_ADD)

__all__ = [
    "HFSS_PROJECT_ACTION_ADD",
    "HFSS_PROJECT_ACTION_NEW",
    "HFSS_PROJECT_ACTIONS",
    "HFSS_PROJECT_MODEL_PER_DESIGN",
    "HFSS_PROJECT_MODEL_SINGLE_AEDT",
    "HFSS_PROJECT_MODELS",
]
